### ISSUE TITLE
Automatic location list issues

### ISSUE THREAD

**Issue by rgrinberg** [ray-x/navigator.lua#37]
Navigator currently sets up the following autocmd:

```
              silent! lua vim.lsp.diagnostic.set_loclist({open_loclist = false})
	Last set from ~/.config/nvim/init.lua
```

But it has a few issues for me:

* The list of filetypes is hard coded and does not correspond to the filetypes I use neovim with lsp.
* Although `open_loclist` is `false`, an empty location list is still opened on every save if there is no language server in the buffer.
* As far as I can tell, there's no way to customize this behavior at all. For example, I don't see how this feature can be turned off.

**Comment by ray-x** [comment]
@rgrinberg 
Is it because the LSP you using does not support diagnostic? What LSP you are using?
I am not sure `The list of filetypes is hard coded and does not correspond to the filetypes I use neovim with lsp.`
The navigator only has a hardcoded blacklist of filetype when the plugin should not be loaded.  It will trying to parse the available filetype and match with LSP. Is there a file type you want to disable? Could you give a example?

**Comment by marcusbuffett** [comment]
Just chiming in here that I seem to be getting this loclist coming up every time I save a buffer that has errors. Don't have any problem w/ updating the loclist on save, but it gets a bit jarring when it opens up so often. Would appreciate a way to disable. Also just wanted to say awesome plugin, it's made navigating through code so much quicker/easier.

**Comment by ray-x** [comment]
Cool, It can be annoying sometime
I put a new config for it:  ` lsp.disply_diagnostic_qf = true `
Please check the document to see if it works for you

**Comment by marcusbuffett** [comment]
Oh shoot, after testing this I've realized it was never the fault of this plugin at all... Turns out prettier is the plugin that was opening the quickfix window. Sorry for the false alarm, and thank you for the added option :+1:

**Comment by ray-x** [comment]
Thanks for the confirmation.
